{% set name = "docspec-python" %}
{% set version = "2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docspec-python-{{ version }}.tar.gz
  sha256: 9bb1bcc2b1e6903d8ef00107607255285d1a1f763acb111f9d83c695878cacbc

build:
  number: 0
  noarch: python
  entry_points:
    - docspec-python = docspec_python.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - docspec >=1.1.0,<2.0.0
    - python >=3.7,<4.0

test:
  imports:
    - docspec_python
  commands:
    - pip check
    - docspec-python --help
  requires:
    - pip

about:
  home: https://pypi.org/project/docspec-python/
  summary: A parser based on lib2to3 producing docspec data from Python source code.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
